### ISSUE TITLE
pdflatex build errors

### ISSUE THREAD

**Issue by aflaus** [af-lab/histone-catalogue#40]
Updated Ubuntu on virtual machine to 16.04.2 LTS just now. Ran git pull and scons -c.

PDF build gives errors:
- "LaTeX Error: Encoding scheme `LGR' unknown."
- Every citation fails with something like "Package natbib Warning: Citation `nomenclature' on page 2 undefined on input line 138."

I checked and "texlive-latex-extra is already the newest version (2015.20160320-1)" so textgreek should be there.

**Comment by carandraug** [comment]
You need to install `texlive-lang-greek`.

`textgreek` is indeed there but it's not in a working state. There is a [packaging bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778917) in newer versions of Debian which is also present in newer versions of Ubuntu. While it installs the textgreek tex package, it does not include `greek-fontenc` which is a dependency of it and is on `texlive-lang-greek` Debian package.

I added a configure check for this.

**Comment by aflaus** [comment]
Worked perfectly thanks.
