### ISSUE TITLE
regex warning with bp_genbank_ref_extractor

### ISSUE THREAD

**Issue by aflaus** [af-lab/histone-catalogue#42]
Warning when refreshing RefSeq

"Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\G{ <-- HERE / at /usr/share/perl5/Bio/ASN1/EntrezGene.pm line 148."

**Comment by carandraug** [comment]
On 28 June 2017 at 23:12, aflaus <notifications@github.com> wrote:
>
> Warning when refreshing RefSeq
>
> "Unescaped left brace in regex is deprecated, passed through in
> regex; marked by <-- HERE in m/\G{ <-- HERE / at
> /usr/share/perl5/Bio/ASN1/EntrezGene.pm line 148."

Hi Andrew

That is a problem with bio-asn1-entrezgene not with our
histone-catalogue.  It has also already been fixed and released in
version 1.71 (released 2016-09-01).  You can ignore the warning but it
will go away once you upgrade the package or your Ubuntu to at least
17.04 (I guess you are still running 16.04).

See
https://github.com/bioperl/Bio-ASN1-EntrezGene/commit/a9b0183ab50ada69046aa4345e598ee41d61965b
for the change.

David
