### ISSUE TITLE
GM test on Ubuntu 16.04 or 17.04?

### ISSUE THREAD

**Issue by aflaus** [af-lab/histone-catalogue#43]
I want to do a final test/how-to for a complete build of the manuscript system starting from vanilla Ubuntu. 

I will ask ISS to rewrite my VM. In principle I know I should use Ubuntu 16.04 LTS. However, there seemed to be a number of supporting libraries that required annoying workarounds to get working on 16.04 whereas the fixes were incorporated in the repositories for 16.10/17.04.

Do you recommend sucking it up with 16.04 LTS, or should I see if ISS will write 17.04?

**Comment by carandraug** [comment]
I think we found that the image you got last time was not a default installation. I can get you a minimal 16:04 and 17:04 image for you to try them and then you can run it on virtual box which also works in OSX. Should I put them on 4big?

**Comment by aflaus** [comment]
I was testing using USB stick installations over the weekend. I'm hoping this will work. I will let you know.

**Comment by aflaus** [comment]
How To instructions for USB installation added in GitHub. Possibly consider virtualbox instructions in future,
