### ISSUE TITLE
Error with empty fetched gene info

### ISSUE THREAD

**Issue by aflaus** [af-lab/histone-catalogue#49]
Appears to be an error with no data from a fetch.
Is this due to a NCBI query issue? Maybe needs an error trap and response?

```
$ scons update manuscript --email=[valid_email]
(passes tests)
This is bp_genbank_ref_extractor on Bioperl 1.007002 on [2020-02-23 16:04:32]
Searching on Entrez gene...
Fetching gene info...
Data Error: none conforming data found on line 1 in input!
first 20 (or till end of input) characters including the non-conforming data:
<error>
        <Code>backe
 at /usr/bin/bp_genbank_ref_extractor line 233.
scons: *** [results/sequences/data.csv] Error 255
scons: building terminated because of errors.
```

**Comment by carandraug** [comment]
For some reason we're receiving timeout errors happening on the NCBI backend.  If I try to download the records manually I get the following:

```
$ curl -s "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=gene&retmode=asn.1&id=8336,8339,8337,8971,115482693,3005,92815,256880,8331,8353,85236,440686,85495,8329,8023,54049,8970,8335,8330,114483833,3009,3007,8348,115482712,3006,373861,317772,3697,3699&rettype=&tool=BioPerl&email=my-email-address&api_key=my-ncbi-apy-key" 
<error>
	<Code>backend-exception</Code>
	<Message>Exception from Backend: beGene (%23GeneBackendSrv): read+request+has+timed+out.+peer%3A+130.14.22.40%3A9997</Message>
</error>
```

The example above even only tries to fetch 30 records but on the histone catalogue we actually fetch almost 300 records. I have sent en email to the NLM help desk reporting this issue and I'm now waiting for an answer.

I have found that there is no timeout for a smaller number of records so worst case scenario we change the program to fetch about 15 records at a time.

**Comment by carandraug** [comment]
I have received a reply from NCBI:

> Thank you for sending helpful data and sorry for the delay. The developers do see a problem with the server, but can't figure how to fix the problem. I was hoping to respond with a "fixed" message, but instead an update. So our programming staff is investigating the issue to determine the cause and we do not have a definite timeline for resolution. We apologize for any inconvenience and appreciate your patience as we try to resolve this issue.

**Comment by carandraug** [comment]
NCBI replied to me saying that it is now fixed. However, I have found that it fails less often but it still fails sometimes.

**Comment by carandraug** [comment]
NCBI replied that there's a timeout global of 5 seconds. With all the histone genes, this sometimes fails but not commonly. This 5 seconds timeout is new. I will make the change on `bp_genbank_ref_extractor`. Closing as there's nothing else to do here.
