### ISSUE TITLE
scons does not recognise option --api-key or --api_key

### ISSUE THREAD

**Issue by aflaus** [af-lab/histone-catalogue#52]
Entrez requests seem to require NCBI personal api_key as noted.

Feeding either --api-key or --api_key to scons gives error 'No such option' so guessing this is not implemented yet?

Hard coding --api_key with value pair in SConstruct as an option for bp_genbank_ref_extractor (eg at line 471) works.

NB Ubuntu 20.04 beta repository has bp_genbank_ref_extractor 1.76 so using underscore not hyphen, and api_key is necessary to avoid bp_genbank_ref_extractor crashing.

**Comment by carandraug** [comment]
This is now implemented but relies on Bio-EUtilites version 1.77 (which is what's included in Debian 12 -- current stable).
